- omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/summary/RegistrationSummaryFragmentController.java
- omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegistrationSummaryPageController.java
- omod/src/main/webapp/fragments/summary/registrationSummary.gsp
- omod/src/main/webapp/fragments/summary/section.gsp
- omod/src/main/webapp/pages/registrationSummary.gsp
caused by hard-coded default registration app instead of the appId passed to the page. The default registration app is updated to referenceapplication.registrationapp.registerPatient
> RA-1298 - Fix Null Pointer exception for Registration Summary page 

- api/src/main/resources/messages.properties
- omod/src/main/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageController.java
- omod/src/test/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageControllerTest.java
- Added fix to support the info message as "Saved changes in _sectionId_ for: _PatientName_", if the sectionId is other than the Contact Info.  
- Added Message property for English.
Ticket Info : https://issues.openmrs.org/browse/RA-1511
> RA-1511 Added fix to support the custom fragment info message for editSection

- omod/src/main/java/org/openmrs/module/registrationapp/RegistrationAppUiUtils.java
- omod/src/main/webapp/fragments/summary/section.gsp
For the ticket https://issues.openmrs.org/browse/RA-1630, i have use the method toString instead of getAttribute to display the Concept Name
> RA-1630:Display Concept Names on Patient Registration Summary instead of Concept IDs

- omod/src/main/webapp/fragments/summary/registrationSummary.gsp
This adds bootstrap styling consistent with the coreapps clinical facing dashboard.  It moves the action menu to the top (see RA-1764) and moves from a 2/3 column layout to a one column layout for easy scrolling and viewing.  Screenshots showing before and after of laptop and emulated mobile view below:
**Registration Summary on Laptop (Before and After)**
**Registration Summary on emulated tablet (Before and After)**
> RA-1765 - Registration Summary should use bootstrap styling

- pom.xml
This should hopefully fix failing builds on Bamboo
> Update to event-api-2.8.0

- omod/src/main/webapp/pages/editSection.gsp
Description of what I did:
I removed 
```
<div class="after-data-canvas"></div>
<div id="confirmationQuestion">
```
on line 222 and 223 to enable the confirm button when editing relationship section.
Issue worked on"
https://issues.openmrs.org/browse/RA-1717
> RA-1717:Cannot save relationship edits: confirm button is not enabled when editing relationships

- omod/src/main/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageController.java
- omod/src/main/webapp/resources/scripts/field/personRelationship.js
Hi @jwamalwa , here is my attempt on fixing this bug with the relationships controller. The code probably needs a bit more cleanup, but I was able to delete and update existing relationships on my local environment.
> RA-1855, update and delete relationships

- README.md
- omod/src/main/webapp/fragments/summary/section.gsp
- omod/src/main/webapp/pages/editSection.gsp
- omod/src/main/webapp/pages/registerPatient.gsp
- omod/src/main/webapp/resources/scripts/registerPatient.js
https://issues.openmrs.org/browse/RA-1898
This just gets rid of the `emr.gender` codes. Eliminating other `emr.` codes are still TODO.
> RA-1898  Reigstration app using old `emr.` message codes - pt 1 - emr.gender

- api/src/test/java/org/openmrs/module/registrationapp/model/SectionTest.java
- api/src/test/resources/registrationAppConfig.json
- api/src/test/resources/section.json
- omod/src/main/webapp/fragments/field/personName.gsp
https://issues.openmrs.org/browse/RA-1898
See [coreapps message.properties](https://github.com/openmrs/openmrs-module-coreapps/blob/master/api/src/main/resources/messages.properties) for reference.
This was previously showing "required" where it now says "necesario"
> RA-1898 Change all 'emr.' message codes to 'coreapps.' equivalents

- omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/summary/RegistrationSummaryFragmentController.java
https://issues.openmrs.org/browse/RA-1806
The ticket required me to replace List ret = new ArrayList() {{ addAll(extensionList); }};
with this:
List ret = new ArrayList();
ret.addAll(extensionList);
which I have done.
The reason for the change is described below:
Because Double Brace Initialization (DBI) creates an anonymous class with a reference to the instance of the owning object, its use can lead to memory leaks if the anonymous inner class is returned and held by other objects. Even when there's no leak, DBI is so obscure that it's bound to confuse most maintainers.
> RA-1806:Double Brace Initialization should not be used

- omod/src/main/webapp/fragments/field/personRelationship.gsp
Hi ,
Made fixes in omod/src/main/webapp/fragments/field/personRelationship.gsp for EMPT-61 fix. Kindly review and let me know the feedback.
Worked along with @The-Lady for solving the issue.
Steps to reproduce :
Launch OpenMRS application using the URL: http://localhost:8080/openmrs
1)Provide the following info and click login​
Username​ as ​admin​ 
Password​ ​ as ​admin123 
Location as ​Inpatient "
2)Click on the “System Administration” module.
3)Click on the “Advance Administration module.
4)Click on “Manage Relationship Types”.
5)Enter <script>alert(1)</script> as the first two text boxes and type in “test” for Description.
6)Hit Save Relationship Type
7)Click on Home.
8) Click on the “Register a Patient” module. A dialogue pops up. Which shouldn't have popped up.
This one only fixes …
> Fixed issue EMPT61 as described in document.

- omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/MatchingPatientsFragmentController.java
**Ticket:** [RA-1922](https://issues.openmrs.org/browse/RA-1922)
**Description:**
When searching for similar patients, there's a list of SimpleObjects with the results. This list is iterated and compared using the patietId. The issue is that the result has no patientId, causing a null pointer ex.
Fixed to comparison to rely on uuid instead.
> RA-1922 - Fixed patient comparison when searching for similar patients

- omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/MatchingPatientsFragmentController.java
- omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/RegisterPatientFragmentController.java
https://issues.openmrs.org/browse/RA-1810
I changed to the isEmpty() method from the size() method because using  the isEmpty()  method makes the code more readable and can be more performant.
> RA-1810: Collection.isEmpty() should be used to test for emptiness

- omod/src/main/java/org/openmrs/module/registrationapp/RegistrationAppUiUtils.java
[[RA-1812] Comparison of String objects using == or !=](https://issues.openmrs.org/browse/RA-1812)
Used the built-in search tool in IntelliJ to find string comparisons and changed the found one from `!=` to `!string1.equals(string2)`
While searching for `Java` string comparisons I found that in some `Javascript` files they have only used `==` where using a `===` comparison is necessary.
> RA-1812 Change comparison method of string of objects to equals()

- omod/src/main/webapp/fragments/field/personAddressWithHierarchy.gsp
- omod/src/main/webapp/resources/scripts/field/personAddressWithHierarchy.js
- omod/src/main/webapp/resources/styles/registerPatient.scss
Hi @mogoodrich , here is my attempt to implement the change we discussed with @mseaton yesterday. This is not complete, I still have a couple corner cases to cover, but just wanted to make sure I am going into the right direction. I think you were the original author of this code, so I you probably have a better sense if this PR is in the accordance with the rest of the code in this widget. Thanks!
Here is screenshot of the address form when selecting a country with no address hierarchy levels:
> UHM-7478, disable address hierarchy levels if there are no entries in the db

- omod/src/main/webapp/resources/scripts/field/personAddressWithHierarchy.js
This is just to fix a bug with editing existing addresses that have empty fields.
> UHM-7478, disable empty levels when editing existing addresses

- api/src/main/java/org/openmrs/module/registrationapp/model/RegisterPersonRelationshipWidget.java
- omod/src/main/webapp/resources/scripts/field/registerPersonRelationship.js
@mogoodrich , I found an easier, more robust way of preventing the user from typing an incorrect person name. I just added an exit handler to the question(that's the reason i needed the question ID) and therefore I am able to prevent the user from moving away from the question if either the search box is not empty or a correct search result was not selected from the list:
> UHM-7476, prevent the user from typing in invalid person names

- omod/src/main/webapp/resources/scripts/field/personAddressWithHierarchy.js
This would basically assure the same behavior as when manually selecting each field individually. The fields will be automatically be disabled if no entries are available in the system:
> UHM-7545, disable address fields if no entries available

- omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java
- omod/src/main/webapp/pages/registerPatient.gsp
@mogoodrich , this is the corresponding PR to the https://github.com/PIH/openmrs-module-pihcore/pull/500
> SL-614, implement fields initial values

- omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/RegisterPatientFragmentController.java
- omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java
- omod/src/main/webapp/fragments/field/registerPersonRelationship.gsp
- omod/src/main/webapp/pages/registerPatient.gsp
- omod/src/test/java/org/openmrs/module/registrationapp/fragment/controller/RegisterPatientFragmentControllerTest.java
Because the person address widget and the relationships widget have onBlur() and onChange() events that get trigger automatically every time the form is displayed, I had to workaround those limitations when the mother info is included in the registration form. Thanks @mogoodrich for reviewing it!
> RA-2037: use mother's info to register a child

- omod/src/main/webapp/pages/registerPatient.gsp
@mogoodrich , I have added the comment you requested about the 'mother-field' field. I have also updated the jQuery statement to only update the fields within the configured question. The relationship widget had two instances configured in out SL registration form, one for capturing the mother info, and another instance to capture the children. Therefore there were multiple fields with the name 'other_person_uuid' and that caused problems. So now I restrict the jQuery select statement to the field name within the given question name.
> RA-2037, update only the fields within the specified question
