omod/src/main/resources/apps/registrationappAppTemplates.json
As recommended in this thread in the Dev group.
https://groups.google.com/a/openmrs.org/forum/#!topic/dev/Gnd_cbpW4xU
=> Changing default value of allowManualIdentifier to false

pom.xml, tools/src/main/resources/eclipse/OpenMRSFormatter.xml
https://issues.openmrs.org/browse/GCI-11
=> Added maven java formatter plugin

api/src/main/resources/messages.properties, omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/RegisterPatientFragmentController.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java, omod/src/main/webapp/fragments/field/personRelationship.gsp, omod/src/main/webapp/pages/registerPatient.gsp, omod/src/main/webapp/resources/scripts/field/personRelationship.js
Patient Relationship Feature: 
- https://issues.openmrs.org/browse/RA-1264
- https://talk.openmrs.org/t/relationships-in-reference-application/8988
@ssmusoke please-fill in the gaps on the issue details and the implementation.
Note: Work In Progress
=> RA-1264 - Added 'Relationship' section on patient registration page to allow addition of person relationships 

omod/src/main/webapp/resources/scripts/field/personAddressWithHierarchy.js
Hi @mogoodrich , here is the small change we talked about it earlier. Thanks!
=> ADDR-111, allow free text entries in PersonAddressWithHierarchy

omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/RegisterPatientFragmentController.java
https://issues.openmrs.org/browse/RA-1430
=> RA-1430: Prevent XSS in pop-up message after patient registration

omod/src/main/webapp/fragments/field/personAddressWithHierarchy.gsp, omod/src/main/webapp/fragments/summary/registrationSummary.gsp, omod/src/main/webapp/pages/biometrics/editBiometrics.gsp, omod/src/main/webapp/pages/editSection.gsp, omod/src/main/webapp/pages/registerPatient.gsp, omod/src/main/webapp/pages/registrationSummary.gsp
https://issues.openmrs.org/browse/RA-1424
=> RA-1424: refactor all instances of ui.escapeJs -> ui.encodeJavaScript

omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java, omod/src/main/webapp/pages/registerPatient.gsp
Ticket : https://issues.openmrs.org/browse/RA-1584
=> RA-1584: All subsections to be configurable to combine as one subsection within their section

.travis.yml, omod/src/main/compass/sass/registerPatient.scss, omod/src/main/webapp/fragments/field/personRelationship.gsp, omod/src/main/webapp/pages/registerPatient.gsp
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now
1.Media queries for register patient page.
2. Registration page ui fixes..
This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592
=> RA-1592 : Boostrap as a foundation for Reference Application UI Project.

omod/src/main/compass/sass/registerPatient.scss
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now
1.Registration page icon-ok width issue fix.
This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592
=> RA-1592 : Boostrap as a foundation for Reference Application UI Project. 

api/src/main/java/org/openmrs/module/registrationapp/model/TextFieldWidget.java
[TextFieldWidget] New attribute, accessor, modifier for regex. Custom regex can be used to validate against value entered in this text field
cc: @mogoodrich
=> [Development] OpenMRS registrationapp TextFieldWidget Regex Config & custom validation error message

omod/src/main/webapp/resources/scripts/registerPatient.js
…checkbox when all sub-sections are combined
Ticket : https://issues.openmrs.org/browse/RA-1584
=> RA-1584: Enable unknown patient checkbox override when all sub-sections are combined

omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java, omod/src/main/webapp/pages/registerPatient.gsp, omod/src/main/webapp/resources/scripts/registerPatient.js
Ticket : https://issues.openmrs.org/browse/RA-1629
=> RA-1629: Adding ability to specify gender options in reg. app definition.

omod/src/main/compass/sass/editSection.scss, omod/src/main/compass/sass/registerPatient.scss, omod/src/main/webapp/pages/editSection.gsp
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now
1.Registration page icon-ok width issue fix.
2. Demographic ui page fix.
This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592
=> RA-1592: Boostrap as a foundation for the Reference Application UI.

omod/src/main/java/org/openmrs/module/registrationapp/form/RegisterPatientFormBuilder.java, omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/summary/SectionFragmentController.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageController.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java, omod/src/test/java/org/openmrs/module/registrationapp/form/RegisterPatientFormBuilderTest.java, omod/src/test/resources/registration_app.json
Related Ticket : https://issues.openmrs.org/browse/RA-1584
=> RA-1584: Reg. App definition sections to be combinable into one.

omod/src/main/compass/sass/editSection.scss, omod/src/main/webapp/pages/editSection.gsp
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes 
3 Demographic ui page save form link issue fixed
This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592
=> RA-1592: Fixes editSection.gsp #save-form element link issue.

omod/src/main/java/org/openmrs/module/registrationapp/RegistrationAppUiUtils.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageController.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java, omod/src/main/webapp/pages/editSection.gsp, omod/src/main/webapp/pages/registerPatient.gsp
Ticket : https://issues.openmrs.org/browse/RA-1629
=> RA-1629: Registration edition to include all configured gender options.

omod/src/main/webapp/fragments/summary/section.gsp, omod/src/main/webapp/pages/editSection.gsp, omod/src/main/webapp/pages/registerPatient.gsp
Ticket : https://issues.openmrs.org/browse/RA-1642
=> RA-1642: Support further PersonName fields as person attributes.

omod/src/main/java/org/openmrs/module/registrationapp/RegistrationAppUiUtils.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageController.java, omod/src/main/webapp/fragments/field/personRelationship.gsp, omod/src/main/webapp/fragments/summary/section.gsp, omod/src/main/webapp/pages/editSection.gsp, omod/src/main/webapp/resources/scripts/editSection.js, omod/src/main/webapp/resources/scripts/field/personRelationship.js, omod/src/test/java/org/openmrs/module/registrationapp/RegistrationAppUiUtilsTest.java, omod/src/test/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageControllerComponentTest.java, omod/src/test/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageControllerTest.java
Ticket : https://issues.openmrs.org/browse/RA-1605
=> RA-1605: Enable editing patient relationships via the edit section page.

omod/src/main/webapp/fragments/field/personAddressWithHierarchy.gsp, omod/src/main/webapp/fragments/summary/registrationSummary.gsp, omod/src/main/webapp/fragments/summary/section.gsp, omod/src/main/webapp/pages/biometrics/editBiometrics.gsp, omod/src/main/webapp/pages/editSection.gsp, omod/src/main/webapp/pages/registerPatient.gsp, omod/src/main/webapp/pages/registrationSummary.gsp
Jira ticket: https://issues.openmrs.org/browse/RA-452
=> RA-452: Remove XSS vulnerabilities

omod/src/main/webapp/pages/registerPatient.gsp, omod/src/main/webapp/resources/scripts/customMultiInputDateValidator.js
Ticket : https://issues.openmrs.org/browse/RA-1710
=> RA-1710: DOB to be required when registration sub-sections are combined.

omod/src/main/webapp/resources/scripts/field/personRelationship.js
Community Ticket: https://issues.openmrs.org/browse/RA-1734
=> RA-734: Relationship section is populated with relationships from existing patients

omod/src/main/webapp/fragments/summary/registrationSummary.gsp, omod/src/main/webapp/fragments/summary/section.gsp
Ticket: https://issues.openmrs.org/browse/RA-452
=> RA-452: (XSS) Encoding HTML before views' HTML substitutions.

omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/field/DropDownFragmentController.java, omod/src/main/webapp/fragments/field/dropDown.gsp, omod/src/test/java/org/openmrs/module/registrationapp/fragment/controller/field/DropDownFragmentControllerTest.java
Ticket: https://issues.openmrs.org/browse/RA-1738
=> RA-1738: Reg. App: DropdownWidget to support concept sets

omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/field/DropDownFragmentController.java, omod/src/test/java/org/openmrs/module/registrationapp/fragment/controller/field/DropDownFragmentControllerTest.java
Follow-on commit to ticket: https://issues.openmrs.org/browse/RA-1738
=> RA-1738: DropdownWidget to merge 'options' and 'conceptSet' options.

omod/src/main/webapp/pages/registerPatient.gsp
Ticket: https://issues.openmrs.org/browse/RA-1757
=> RA-1757: Registration DOB field to have the (required) tip.

omod/src/main/java/org/openmrs/module/registrationapp/RegistrationAppUiUtils.java, omod/src/main/webapp/fragments/field/personRelationship.gsp, omod/src/main/webapp/fragments/summary/section.gsp, omod/src/test/java/org/openmrs/module/registrationapp/RegistrationAppUiUtilsTest.java
Ticket: https://issues.openmrs.org/browse/RA-1742
=> RA-1742: Relationship type names to be localisable.

omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/field/DropDownFragmentController.java, omod/src/test/java/org/openmrs/module/registrationapp/fragment/controller/field/DropDownFragmentControllerTest.java
Ticket: https://issues.openmrs.org/browse/RA-1738
=> RA-1738: field/dropDown widget String options sorted alphabetically.

api/src/main/java/org/openmrs/module/registrationapp/model/Question.java, api/src/main/java/org/openmrs/module/registrationapp/model/Section.java, omod/src/main/java/org/openmrs/module/registrationapp/form/RegisterPatientFormBuilder.java, omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/MatchingPatientsFragmentController.java, omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/RegisterPatientFragmentController.java, omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/summary/BiometricsSummaryFragmentController.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/biometrics/EditBiometricsPageController.java, omod/src/test/java/org/openmrs/module/registrationapp/form/RegisterPatientFormBuilderTest.java, omod/src/test/java/org/openmrs/module/registrationapp/fragment/controller/RegisterPatientFragmentControllerTest.java, omod/src/test/resources/registration_app_with_require.json, pom.xml
This PR is for partial support of RA-1766, which adds the "require" property from the AppFramework to the registration app. The foundation for this PR is [this PR against the AppFramework](https://github.com/openmrs/openmrs-module-appframework/pull/49). This PR builds on that to add support for the "require" property to the registration app section and questions.
=> RA-1766: Update Section and Question to support a "require" parameter

omod/src/main/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageController.java
Related Issue: https://issues.openmrs.org/browse/RA-1779
=> RA-1779: Success message L10n when patient edited & saved.

omod/src/main/webapp/pages/registerPatient.gsp
Related ticket: https://issues.openmrs.org/browse/RA-1773
Related PR with changes in uicommons module - https://github.com/openmrs/openmrs-module-uicommons/pull/82
=> RA-1773: Corrected inconsistencies with 'require' label

omod/src/main/java/org/openmrs/module/registrationapp/form/RegisterPatientFormBuilder.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/RegisterPatientPageController.java
Link to JIRA ticket https://issues.openmrs.org/browse/RA-1804
=> RA-1804:Unnecessary imports should be removed

omod/src/main/java/org/openmrs/module/registrationapp/form/RegisterPatientFormBuilder.java
Link to the JIRA ticket: https://issues.openmrs.org/browse/RA-1807
=> RA-1807:Modifiers should be declared in the correct order

omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/field/DropDownFragmentController.java
Link to ticket https://issues.openmrs.org/browse/RA-1803
=> RA-1803:Unused assignments should be removed

omod/src/main/webapp/resources/scripts/registerPatient.js
RA-1861 - The relationships field is now grey-lined / disabled
=> RA-1861: Clear and disable relationships for unknown patients.

omod/src/main/java/org/openmrs/module/registrationapp/form/RegisterPatientFormBuilder.java, omod/src/test/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageControllerComponentTest.java
This is just a unit test to illustrate the bug documented in RA-1883. I will add a code fix too.
=> RA-1883, add unit test to demonstrate the problem

omod/src/main/java/org/openmrs/module/registrationapp/RegistrationAppUiUtils.java
Related ticket:
https://issues.openmrs.org/browse/RA-1787
=> RA-1787: More specific validation error for patient identifier field

omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/RegisterPatientFragmentController.java
Ticket Id: https://issues.openmrs.org/browse/RA-1811
=> RA-1811: 'toString()' should never be called on a String object

api/src/main/java/org/openmrs/module/registrationapp/model/DropdownWidget.java, api/src/test/java/org/openmrs/module/registrationapp/model/DropdownWidgetTest.java, api/src/test/resources/dropdown.json
Depends on https://github.com/openmrs/openmrs-module-uicommons/pull/87
=> Add autocomplete option for dropdown widget

api/src/main/java/org/openmrs/module/registrationapp/model/NavigableFormStructure.java
https://issues.openmrs.org/browse/RA-1802
I have removed unused local variables.
This is because if a local variable is declared but not used, it is dead code. Removing this will improve maintainability because developers will not wonder what the variable is used for.
=> RA-1802:Un used local variables should be removed

omod/src/main/webapp/resources/scripts/field/personRelationship.js
Hi Team,
@isears @ibacher 
Made changes to Fix EMPT 61 and EMPT171 and handle Relatives block explicitly.
This is my third try to fix EMPT171 which Handled the edge case explicitly and properly. The first PR for the same issue was https://github.com/openmrs/openmrs-module-uicommons/pull/89 and the second Pr was https://github.com/openmrs/openmrs-module-uicommons/pull/91.
For EMPT171 :-
i) Go to Register a Patient
ii) Enter <SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT> in all the input fields in the form if client side validator allows it
Press Confirm from the left menu.
Link to ticket
RA-1875 (https://issues.openmrs.org/browse/RA-1875)
@isears
=> Made changes to remove XSS in displayValue param

omod/src/main/webapp/fragments/field/personRelationship.gsp
I have encoded the patient name to prevent xss
before:
After
cc @isears @sherrif10
=> MM-876: XSS in relation name (input validation)

omod/src/main/java/org/openmrs/module/registrationapp/RegistrationAppUiUtils.java, omod/src/main/java/org/openmrs/module/registrationapp/fragment/controller/summary/RegistrationSummaryFragmentController.java, omod/src/main/java/org/openmrs/module/registrationapp/page/controller/EditSectionPageController.java
https://issues.openmrs.org/browse/RA-1808
Merged collapsible if statements in the codebase
=> RA-1808: Collapsible 'if' statements should be merged

omod/src/main/webapp/fragments/field/registerPersonRelationship.gsp, omod/src/main/webapp/resources/scripts/field/registerPersonRelationship.js
@mogoodrich , I was able to get all selected children displayed on the Confirmation page:
=> UHM-7475, display all selected relationships

omod/src/main/webapp/resources/scripts/field/registerPersonRelationship.js
@mogoodrich , finally I was able to get this validation working. The following code will force the user to select a valid entry from the search results or clear the input box:
=> UHM-7476, prevent user from entering invalid relationship value

omod/src/main/webapp/resources/scripts/field/registerPersonRelationship.js
Display the patient identifier and DOB in the search results:
=> UHM-7518, display patient identifier and DOB in search results

omod/src/main/webapp/fragments/field/registerPersonRelationship.gsp, omod/src/main/webapp/resources/scripts/field/registerPersonRelationship.js
@mogoodrich , here I am just keeping track of the item label selected from the search results, and then compare this value with the value typed in by the user to make sure we are not moving away from this question until a valid item is selected from the list or the input box is empty. Thanks!
=> UHM-7476, keep track of the value selected from the search results

omod/src/main/webapp/resources/scripts/biometrics/fingerprintSearchController.js
@mogoodrich, @mseaton Please review this PR
=> Added 'search:start' event to trigger the start of a search during fIngerprint scanning
